
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.burnt]
			smoldering_bamboo = true
			burnt = true
			smoldering = true
			burnt_bamboo = true
			ember = true
			sooty_oak = true
			sooty_dark_oak = true
			sooty_spruce = true
			sooty_birch = true
			sooty_acacia = true
			sooty_mangrove = true
			sooty_cherry = true
			sooty_jungle = true
			blazing = true

		[types.wood_type.netherexp]
			claret = true
			smokestalk = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.vanillabackport]
			pale_oak = true

		[types.wood_type.foolish]
			melancholic_wood = true
			aspen = true
			daybright = true
			surge = true
			carmine = true
			murken = true
			ashen = true
			darkleaf = true
			radiant = true
			timewood = true
			ribtree = true
			flickerwood = true
			cascade = true

		[types.wood_type.cataclysm]
			chorus = true

	[types.leaves_type]

		[types.leaves_type.vanillabackport]
			pale_oak = true

		[types.leaves_type.burnt]
			burnt = true
			smoldering = true
			smoldering_oak = true
			smoldering_dark_oak = true
			smoldering_spruce = true
			smoldering_birch = true
			smoldering_jungle = true
			smoldering_mangrove = true
			smoldering_cherry = true
			smoldering_acacia = true
			blast = true

		[types.leaves_type.foolish]
			frigid = true
			surge = true
			radiant = true
			timewood = true
			ribtree = true
			flickerwood = true
			cascade = true
			nightshade = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.farmersdelight]
			cabinet = true

