
[animations]
	#Choose your preferred animation speed (1-15)
	#Range: 1.0 ~ 15.0
	animationSpeed = 1.0
	#Enable or disable swimming animation
	enableSwimmingAnimation = true
	#Swing animation speed (6-12)
	#Range: 6 ~ 12
	swingSpeed = 9
	#Enable or disable climb and crawl animation
	enableClimbAndCrawlAnimation = true
	#Enable or disable punching animation
	enablePunchingAnimation = true

[positions]
	#Viewmodel X Offset
	#Range: -10.0 ~ 10.0
	viewmodelXOffset = 0.0
	#Viewmodel Y Offset
	#Range: -10.0 ~ 10.0
	viewmodelYOffset = 0.0
	#Viewmodel Z Offset
	#Range: -10.0 ~ 10.0
	viewmodelZOffset = 0.0

[misc]
	#Enable MB3D compatibility mode
	mb3DCompat = false

[modRenderExclusions]
	#List of mod IDs whose items handle their own first-person rendering. Hold My Items will skip its custom logic when such an item is held.
	modsThatHandleTheirOwnRendering = ["pointblank", "jeg"]

[itemRenderExclusions]
	#List of items to disable custom rendering for. Can use patterns with * as wildcard.
	disabledItems = []
	#List of items to disable custom 3rd person rendering for. Can use patterns with * as wildcard.
	thirdPersonBlacklist = []

